remote_theme: b2a3e8/jekyll-theme-console

title: "Lorenzo Sciarretta"
description: "MSc in Computer Science, Graduate Researcher"

show_downloads: ["true"]


header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: hacker

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown

darkmode: false
hide_first_title: false # Useful if README.md is used on both github and pages
logo_url: ./logo.png # Either absolute or relative url
syntax_theme: ./syntax.css # Leave empty for default, otherwise link to a pygments stylesheet

colors:
    gradient_left: "#1f2937"       # Grigio scuro
    gradient_right: "#3b82f6"      # Azzurro chiaro
    header: "#ffffff"              # Bianco
    android_theme: "#1f2937"       # Grigio scuro
    link: "#10b981"                # Verde menta
    section_title: "#3b82f6"       # Azzurro chiaro

buttons:
      zip_url: https://github.com/L-Neur0
      zip_title: ["GitHub"]
      zip_hide: false
      tar_url: http://example.com/
      tar_title: Title
      tar_hide: true
      github_hide: true # hides "View on Github"
      
navbar:
  - name: ["Home"]
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Projects"
    link: "/projects"
  - name: "Contact"
    link: "/contact"
  - name: "GitHub"
    link: "https://github.com/tuo-username"
  - name: "LinkedIn"
    link: "https://www.linkedin.com/in/LorenzoSciarretta/"
