remote_theme: tuur29/pages-themes-cayman

title: [Lorenzo Sciarretta]
description: [Msc in Computer Science, Graduate Researcher]

show_downloads: false
darkmode: true
hide_first_title: false
logo_url: ./logo.png
syntax_theme: ./syntax.css

colors:
  gradient_left: "#1E40AF"  # Deep blue
  gradient_right: "#3B82F6"  # Lighter blue
  header: "#FFFFFF"
  android_theme: "#1E40AF"
  link: "#3B82F6"
  section_title: "#1E40AF"

buttons:
  github_hide: false

navbar:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Projects"
    link: "/projects"
  - name: "Contact"
    link: "/contact"
  - name: "GitHub"
    link: "https://github.com/your-username"
  - name: "LinkedIn"
    link: "https://www.linkedin.com/in/your-username/"

footer:
  - name: "GitHub"
    link: "https://github.com/your-username"
    icon: "fab fa-github"
  - name: "LinkedIn"
    link: "https://www.linkedin.com/in/your-username/"
    icon: "fab fa-linkedin"
