remote_theme: tuur29/pages-themes-cayman


title: [Lorenzo Sciarretta]
description: [Msc in Computer Science , Graduate Reseacher]


show_downloads: ["true"]

darkmode: true
hide_first_title: false # Useful if README.md is used on both github and pages
logo_url: ./logo.png # Either absolute or relative url
syntax_theme: ./syntax.css # Leave empty for default, otherwise link to a pygments stylesheet
colors:
    gradient_left: "#000000"     # Sfondo nero
    gradient_right: "#000000"    # Sfondo nero
    header: "#ffffff"            # Testo bianco per l'intestazione
    android_theme: "#000000"     # Tema Android nero
    link: "#ffffff"              # Link bianchi
    section_title: "#ffffff"     # Titoli delle sezioni bianchi

buttons:
      zip_url: http://example.com/
      zip_title: Title
      zip_hide: true
      tar_url: http://example.com/
      tar_title: Title
      tar_hide: true
      github_hide: true # hides "View on Github"


