
remote_theme: b2a3e8/jekyll-theme-console

show_downloads: ["true"]
style: dark
custom_css: /assets/style.css

header_pages:
  - index.md
  - lorenzo.md
  - about.md
  - contact.md

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'
<style>
  img {
    border-radius: 50%;
    width: 150px;
    height: 150px;
    object-fit: cover;
  }
</style>

![Lorenzo](./foto.jpg)

# Build settings
markdown: kramdown

darkmode: false
hide_first_title: false # Useful if README.md is used on both github and pages
logo_url: ./logo.png # Either absolute or relative url
syntax_theme: ./syntax.css # Leave empty for default, otherwise link to a pygments stylesheet

# Includere il CSS personalizzato
plugins:
  - jekyll-remote-theme
